# Traffic Violation RAG System
In this exam, you will implement a Retrieval-Augmented Generation (RAG) system that uses a language model and a vector database to answer questions about traffic violations. The goal is to generate answers with relevant data based on a dataset of traffic violations and fines.

Here are helpful resources:
* [LangChain](https://www.langchain.com/)
* [groq cloud documentation](https://console.groq.com/docs/models)
* [LangChain HuggingFace](https://python.langchain.com/docs/integrations/text_embedding/sentence_transformers/)
* [Chroma Vector Store](https://python.langchain.com/docs/integrations/vectorstores/chroma/)
* [Chroma Website](https://docs.trychroma.com/getting-started)
* [ChatGroq LangChain](https://python.langchain.com/docs/integrations/chat/groq/)
* [LLM Chain](https://api.python.langchain.com/en/latest/chains/langchain.chains.llm.LLMChain.html#langchain.chains.llm.LLMChain)

Dataset [source](https://www.moi.gov.sa/wps/portal/Home/sectors/publicsecurity/traffic/contents/!ut/p/z0/04_Sj9CPykssy0xPLMnMz0vMAfIjo8ziDTxNTDwMTYy83V0CTQ0cA71d_T1djI0MXA30gxOL9L30o_ArApqSmVVYGOWoH5Wcn1eSWlGiH1FSlJiWlpmsagBlKCQWqRrkJmbmqRqUZebngB2gUJAKdERJZmqxfkG2ezgAhzhSyw!!/)

Some installs if needed:
```python
!pip install langchain_huggingface langchain langchain-community langchain_chroma Chroma langchain_groq LLMChain
```

In [ ]:
!kaggle datasets download -d khaledzsa/dataset
!unzip dataset.zip

Dataset URL: https://www.kaggle.com/datasets/khaledzsa/dataset
License(s): unknown
Downloading dataset.zip to /content
  0% 0.00/3.73k [00:00<?, ?B/s]
100% 3.73k/3.73k [00:00<00:00, 5.82MB/s]
Archive:  dataset.zip
  inflating: Dataset.csv

## Step 1: Install Required Libraries

To begin, install the necessary libraries for this project. The libraries include `LangChain` for building language model chains, and `Chroma` for managing a vector database.

In [ ]:
!pip install --upgrade gradio

Collecting gradio
  Downloading gradio-5.3.0-py3-none-any.whl.metadata (15 kB)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.7.1)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.115.3-py3-none-any.whl.metadata (27 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.4.0-py3-none-any.whl.metadata (2.9 kB)
Collecting gradio-client==1.4.2 (from gradio)
  Downloading gradio_client-1.4.2-py3-none-any.whl.metadata (7.1 kB)
Collecting httpx>=0.24.1 (from gradio)
  Downloading httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting huggingface-hub>=0.25.1 (from gradio)
  Downloading huggingface_hub-0.26.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.1.4)
Collecting markupsafe~=2.0 (from gradio)
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.26.4)
Collecting orjson~=3.0 (from gradio)
  Downloading orjson-3.10.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio) (24.1)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<11.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (10.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.9.2)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.9 (from gradio)
  Downloading python_multipart-0.0.12-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.0.2)
Collecting ruff>=0.2.2 (from gradio)
  Downloading ruff-0.7.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.41.0-py3-none-any.whl.metadata (6.0 kB)
Collecting tomlkit==0.12.0 (from gradio)
  Downloading tomlkit-0.12.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.12.5)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.32.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.4.2->gradio) (2024.6.1)
Collecting websockets<13.0,>=10.0 (from gradio-client==1.4.2->gradio)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (2024.8.30)
Collecting httpcore==1.* (from httpx>=0.24.1->gradio)
  Downloading httpcore-1.0.6-py3-none-any.whl.metadata (21 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.24.1->gradio)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (3.16.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (4.66.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (2.23.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.2.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-5.3.0-py3-none-any.whl (56.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 MB 9.9 MB/s eta 0:00:00
Downloading gradio_client-1.4.2-py3-none-any.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.8/319.8 kB 17.3 MB/s eta 0:00:00
Downloading tomlkit-0.12.0-py3-none-any.whl (37 kB)
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading fastapi-0.115.3-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 6.5 MB/s eta 0:00:00
Downloading httpx-0.27.2-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 4.1 MB/s eta 0:00:00
Downloading httpcore-1.0.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 5.1 MB/s eta 0:00:00
Downloading huggingface_hub-0.26.1-py3-none-any.whl (447 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.4/447.4 kB 25.2 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Downloading orjson-3.10.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.5/144.5 kB 10.9 MB/s eta 0:00:00
Downloading python_multipart-0.0.12-py3-none-any.whl (23 kB)
Downloading ruff-0.7.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 79.7 MB/s eta 0:00:00
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.41.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 4.7 MB/s eta 0:00:00
Downloading uvicorn-0.32.0-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 4.1 MB/s eta 0:00:00
Downloading ffmpy-0.4.0-py3-none-any.whl (5.8 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.8 MB/s eta 0:00:00
Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 8.7 MB/s eta 0:00:00
Installing collected packages: pydub, websockets, tomlkit, semantic-version, ruff, python-multipart, orjson, markupsafe, h11, ffmpy, aiofiles, uvicorn, starlette, huggingface-hub, httpcore, httpx, fastapi, gradio-client, gradio
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.24.7
    Uninstalling huggingface-hub-0.24.7:
      Successfully uninstalled huggingface-hub-0.24.7
Successfully installed aiofiles-23.2.1 fastapi-0.115.3 ffmpy-0.4.0 gradio-5.3.0 gradio-client-1.4.2 h11-0.14.0 httpcore-1.0.6 httpx-0.27.2 huggingface-hub-0.26.1 markupsafe-2.1.5 orjson-3.10.10 pydub-0.25.1 python-multipart-0.0.12 ruff-0.7.0 semantic-version-2.10.0 starlette-0.41.0 tomlkit-0.12.0 uvicorn-0.32.0 websockets-12.0

In [ ]:
!pip install langchain_huggingface langchain langchain-community langchain_chroma Chroma langchain_groq

Collecting langchain_huggingface
  Downloading langchain_huggingface-0.1.0-py3-none-any.whl.metadata (1.3 kB)
Collecting langchain
  Downloading langchain-0.3.4-py3-none-any.whl.metadata (7.1 kB)
Collecting langchain-community
  Downloading langchain_community-0.3.3-py3-none-any.whl.metadata (2.8 kB)
Collecting langchain_chroma
  Downloading langchain_chroma-0.1.4-py3-none-any.whl.metadata (1.6 kB)
Collecting Chroma
  Downloading Chroma-0.2.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Collecting langchain_groq
  Downloading langchain_groq-0.2.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from langchain_huggingface) (0.26.1)
Collecting langchain-core<0.4,>=0.3.0 (from langchain_huggingface)
  Downloading langchain_core-0.3.12-py3-none-any.whl.metadata (6.3 kB)
Collecting sentence-transformers>=2.6.0 (from langchain_huggingface)
  Downloading sentence_transformers-3.2.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: tokenizers>=0.19.1 in /usr/local/lib/python3.10/dist-packages (from langchain_huggingface) (0.19.1)
Requirement already satisfied: transformers>=4.39.0 in /usr/local/lib/python3.10/dist-packages (from langchain_huggingface) (4.44.2)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.0.36)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (3.10.10)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (4.0.3)
Collecting langchain-text-splitters<0.4.0,>=0.3.0 (from langchain)
  Downloading langchain_text_splitters-0.3.0-py3-none-any.whl.metadata (2.3 kB)
Collecting langsmith<0.2.0,>=0.1.17 (from langchain)
  Downloading langsmith-0.1.137-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.9.2)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (9.0.0)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain-community)
  Downloading pydantic_settings-2.6.0-py3-none-any.whl.metadata (3.5 kB)
Collecting chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0 (from langchain_chroma)
  Downloading chromadb-0.5.15-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: fastapi<1,>=0.95.2 in /usr/local/lib/python3.10/dist-packages (from langchain_chroma) (0.115.3)
Collecting groq<1,>=0.4.1 (from langchain_groq)
  Downloading groq-0.11.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.16.0)
Collecting build>=1.0.3 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting chroma-hnswlib==0.7.6 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading chroma_hnswlib-0.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]>=0.18.3->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (0.32.0)
Collecting posthog>=2.4.0 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading posthog-3.7.0-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (4.12.2)
Collecting onnxruntime>=1.14.1 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading onnxruntime-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.16.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.27.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_instrumentation_fastapi-0.48b0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.16.0)
Collecting pypika>=0.48.9 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (4.66.5)
Collecting overrides>=7.3.1 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (6.4.5)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.64.1)
Collecting bcrypt>=4.0.1 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (0.12.5)
Collecting kubernetes>=28.1.0 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading kubernetes-31.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting mmh3>=4.0.1 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading mmh3-5.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (3.10.10)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (0.27.2)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (13.9.2)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading marshmallow-3.23.0-py3-none-any.whl.metadata (7.6 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: starlette<0.42.0,>=0.40.0 in /usr/local/lib/python3.10/dist-packages (from fastapi<1,>=0.95.2->langchain_chroma) (0.41.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from groq<1,>=0.4.1->langchain_groq) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from groq<1,>=0.4.1->langchain_groq) (1.7.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from groq<1,>=0.4.1->langchain_groq) (1.3.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->langchain_huggingface) (24.1)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.4,>=0.3.0->langchain_huggingface)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting requests-toolbelt<2.0.0,>=1.0.0 (from langsmith<0.2.0,>=0.1.17->langchain)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.23.4)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain-community)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2024.8.30)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (2.5.0+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (1.5.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (1.13.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=2.6.0->langchain_huggingface) (10.4.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.1.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.39.0->langchain_huggingface) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.39.0->langchain_huggingface) (0.4.5)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->groq<1,>=0.4.1->langchain_groq) (1.2.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (2.0.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.0.6)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (0.14.0)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core<0.4,>=0.3.0->langchain_huggingface)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.8.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (3.2.2)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (24.3.25)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.13.1)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.2.14)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (75.1.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.65.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.27.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_exporter_otlp_proto_common-1.27.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.27.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_proto-1.27.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_sdk-1.27.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-instrumentation-asgi==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_instrumentation_asgi-0.48b0-py3-none-any.whl.metadata (2.0 kB)
Collecting opentelemetry-instrumentation==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_instrumentation-0.48b0-py3-none-any.whl.metadata (6.1 kB)
Collecting opentelemetry-semantic-conventions==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_semantic_conventions-0.48b0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-util-http==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_util_http-0.48b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.16.0)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading opentelemetry_api-1.27.0-py3-none-any.whl.metadata (1.4 kB)
Collecting importlib-metadata<=8.4.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading importlib_metadata-8.4.0-py3-none-any.whl.metadata (4.7 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (2.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.0->langchain_huggingface) (3.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.3.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma) (1.5.4)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.18.3->chromadb!=0.5.4,!=0.5.5,<0.6.0,>=0.4.0->langchain_chroma)

In [ ]:
%pip install -qU langchain-text-splitters

In [ ]:
import pandas as pd
import os
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain_chroma import Chroma
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_groq import ChatGroq
import markdown
import gradio as gr
from langchain.docstore.document import Document
from langchain_huggingface import HuggingFaceEmbeddings

# Step 2: Load the Traffic Violations Dataset

You are provided with a dataset of traffic violations. Load the CSV file into a pandas DataFrame and preview the first few rows of the dataset.

In [ ]:
df = pd.read_csv('Dataset.csv')
df

,المخالفة,الغرامة
0,قيادة المركبة في الأسواق التي لا يسمح بالقيادة...,الغرامة المالية 100 - 150 ريال
1,ترك المركبة مفتوحة وفي وضع التشغيل بعد مغادرتها.,الغرامة المالية 100 - 150 ريال
2,عدم وجود تأمين ساري للمركبة.,الغرامة المالية 100 - 150 ريال
3,عبور المشاة للطرق من غير الأماكن المخصصة لهم.,الغرامة المالية 100 - 150 ريال
4,عدم تقيد المشاة بالإشارات الخاصة بهم.,الغرامة المالية 100 - 150 ريال
...,...,...
99,القيام بأعمال الطرق قبل التنسيق مع الإدارة الم...,الغرامة المالية 5000 - 10000 ريال
100,سماح أصحاب الحيوانات بعبور حيواناتهم من غير ال...,الغرامة المالية 5000 - 10000 ريال
101,استخدام لوحات غير عائدة للمركبة.,الغرامة المالية 5000 - 10000 ريال
102,طمس رقم هيكل المركبة أو محاولة طمسه.,الغرامة المالية 5000 - 10000 ريال
103,المجازفة بعبور الأودية والشعاب أثناء جريانها.,الغرامة المالية 5000 - 10000 ريال

In [ ]:
df.isna().sum()

المخالفة    0
الغرامة     0
dtype: int64

In [ ]:
df.duplicated().sum()

0

Find the maximum length of the strings in the column `'المخالفة'` in a DataFrame df

In [ ]:
df['المخالفة'].str.len().max()

141

Find the maximum length of the strings in the column `'الغرامة'` in a DataFrame df

In [ ]:
df['الغرامة'].str.len().max()

33

## Step 3: Create Markdown Content from the Dataset

For each traffic violation in the dataset, you will generate markdown text that describes the violation and the associated fine. Create a loop to iterate through the dataset and store the generated markdown in a list. Each fine should look like this:

**المخالفة** - الغرامة

In [ ]:
directory = 'markdown_files'
os.makedirs(directory, exist_ok=True)

In [ ]:
violations = df['المخالفة']
palanties = df['الغرامة']

for i in range(len(df)):
  violation = violations.iloc[i]
  palanty = palanties.iloc[i]

  markdown_text = f'# {violation}\n'
  markdown_text += f'{palanty}'

  with open(f'{directory}/{i}.md', 'w', encoding='utf-8') as file:
    file.write(markdown_text)

## Step 4: Creating Documents

We will read Markdown files from a specified directory, convert their content to HTML, create Document objects, and demonstrate the process by printing the first document.

In [ ]:
marked_text = []
for filename in os.listdir(directory):
  if filename.endswith('.md'):
     with open(os.path.join(directory, filename), 'r', encoding='utf-8') as file:
      temp = file.read()
      html_text = markdown.markdown(temp)
      marked_text.append(html_text)

In [ ]:
marked_text[:10]

['<h1>عدم قيام السائق في حال تغيير اتجاهه بالدوران للخلف بإعطاء أفضلية المرور للمركبات القادمة من الاتجاهات الأخرى.</h1>\n<p>الغرامة المالية 500 - 900 ريال</p>',
 '<h1>القيادة على الطريق بمركبات مخصصة للاقتناء.</h1>\n<p>الغرامة المالية 500 - 900 ريال</p>',
 '<h1>عبور المشاة للطرق السريعة.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>',
 '<h1>إجراء سباق للمركبات على الطرق العامة، أو السير في مواكب دون الحصول على تصريح.</h1>\n<p>الغرامة المالية 3000 - 6000 ريال</p>',
 '<h1>عبور المشاة للطرق من غير الأماكن المخصصة لهم.</h1>\n<p>الغرامة المالية 100 - 150 ريال</p>',
 '<h1>تجاوز حافلات النقل المدرسي عند توقفها للتحميل أو التنزيل.</h1>\n<p>الغرامة المالية 3000 - 6000 ريال</p>',
 '<h1>عدم قيام السائق في حال إغلاق جزء من الطريق بإعطاء الأفضلية لمن كان طريقه مفتوحاً.</h1>\n<p>الغرامة المالية 500 - 900 ريال</p>',
 '<h1>ترك أجسام على الطرق العامة تعرض السلامة العامة للخطر.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>',
 '<h1>عدم تقديم المركبة للفحص الفني الدوري.</h1>\n<p>الغرامة المالية 150 - 300 ريال</p>',
 '<h1>عدم استخدام مقاعد الأمان المخصصة للأطفال.</h1>\n<p>الغرامة المالية 300 - 500 ريال</p>']

In [ ]:
documents = []
for text in marked_text:
    document = Document(page_content=text)
    documents.append(document)

# Print the first document
print(documents[0])

page_content='<h1>عدم قيام السائق في حال تغيير اتجاهه بالدوران للخلف بإعطاء أفضلية المرور للمركبات القادمة من الاتجاهات الأخرى.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>'

## Step 5: Generate Embeddings for the Documents

Generate embeddings for the chunks of text using HuggingFace's pre-trained Arabic language model. These embeddings will be stored in a `Chroma` vector store.

In [ ]:
embeddings = HuggingFaceEmbeddings(model_name="Omartificial-Intelligence-Space/GATE-AraBert-v0")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/205 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/7.50k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/672 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/541M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.02k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/761k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.78M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

In [ ]:
arabic_VDB = Chroma.from_documents(documents, embeddings, persist_directory="./chroma_db")

# Step 6: Define the RAG Prompt Template

Define a custom prompt template in Arabic to retrieve traffic violation-related answers based on the context. Ensure the template encourages the model to give **advice** in **Arabic**, staying within the context provided.

In [ ]:
prompt = """
## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: {المخالفة}
السؤال: {السؤال}
جوابك:
"""

arabic_prompt = PromptTemplate(
    template=prompt, input_variables= ["المخالفة", "السؤال"]
)

## Step 7: Initialize the Language Model

Initialize the language model using the Groq API. Set up the model with a specific configuration, including the API key, temperature setting, and model name.

In [ ]:
key_API = 'API_KEY'

In [ ]:
LLM = ChatGroq(temperature=0, groq_api_key=key_API, model_name="llama3-70b-8192")

## Step 8: Create the LLM Chain

Now, you will create an LLM Chain that combines the language model and the prompt template you defined. This chain will be used to generate responses based on the retrieved context.

In [ ]:
model = LLMChain(llm=LLM, prompt=arabic_prompt, verbose=True)

<ipython-input-21-8c797a5007e1>:1: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  model = LLMChain(llm=LLM, prompt=arabic_prompt, verbose=True)

## Step 9: Implement the Query Function

Create a function `query_rag` that will take a user query as input, retrieve relevant context from the vector store, and use the language model to generate a response based on that context.

In [ ]:
def query_rag(query: str):
    results = arabic_VDB.similarity_search_with_score(query, k=4)
    context_text = "\n\n".join([doc.page_content for doc, score in results if score > 0.5])
    rag_response = model.invoke({"المخالفة": context_text, "السؤال": query})
    return rag_response , results

## Step 10: Inference - Running Queries in the RAG System

In this final step, you will implement an inference pipeline to handle real-time queries. You will allow the system to retrieve the most relevant violations and fines based on a user's input and generate a response.

1. Inference Workflow:

  * The user inputs a query (e.g., "ماهي الغرامة على القيادة بدون رخصة؟").
  * The system searches for the most relevant context from the traffic violation vector store.
  * It generates an answer and advice based on the context.

2. Goal:
  * Run the inference to answer questions based on the traffic violation dataset.

In [ ]:
res, docs = query_rag( 'ماهي الغرامة على القيادة بدون رخصة؟')
res

> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع استخدامها.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح والأنوار وما في حكمهما.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1>
<p>الغرامة المالية 150 - 300 ريال</p>

<h1>وضع كتابة أو رسم أو ملصق أو أي بيان آخر على جسم المركبة دون موافقة الجهات المختصة.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>
السؤال: ماهي الغرامة على القيادة بدون رخصة؟
جوابك:


> Finished chain.

{'المخالفة': '<h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع استخدامها.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح والأنوار وما في حكمهما.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1>\n<p>الغرامة المالية 150 - 300 ريال</p>\n\n<h1>وضع كتابة أو رسم أو ملصق أو أي بيان آخر على جسم المركبة دون موافقة الجهات المختصة.</h1>\n<p>الغرامة المالية 500 - 900 ريال</p>',
 'السؤال': 'ماهي الغرامة على القيادة بدون رخصة؟',
 'text': 'تتراوح غرامة القيادة بدون رخصة بين 1000 و2000 ريال سعودي. ننصحك بالحصول على رخصة قيادة سارية المفعول قبل قيادة المركبة، حيث أن القيادة بدون رخصة تهدد سلامتك وسلامة الآخرين.'}

In [ ]:
res2, docs2 = query_rag( 'ما هي غرامة عدم حمل رخصة القيادة اثناء القياده؟')
res2

> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1>
<p>الغرامة المالية 150 - 300 ريال</p>

<h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع استخدامها.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح والأنوار وما في حكمهما.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>عدم إعطاء أفضلية المرور في ملتقيات الطرق أو تقاطعاتها لسائق المركبة المتقدم على غيره في حال عدم وجود لوحات تنظم ذلك.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>
السؤال: ما هي غرامة عدم حمل رخصة القيادة اثناء القياده؟
جوابك:


> Finished chain.

{'المخالفة': '<h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1>\n<p>الغرامة المالية 150 - 300 ريال</p>\n\n<h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع استخدامها.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح والأنوار وما في حكمهما.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>عدم إعطاء أفضلية المرور في ملتقيات الطرق أو تقاطعاتها لسائق المركبة المتقدم على غيره في حال عدم وجود لوحات تنظم ذلك.</h1>\n<p>الغرامة المالية 500 - 900 ريال</p>',
 'السؤال': 'ما هي غرامة عدم حمل رخصة القيادة اثناء القياده؟',
 'text': 'تتراوح غرامة عدم حمل رخصة القيادة أثناء القيادة بين 150 و300 ريال سعودي. ننصحك بالحفاظ على رخصة القيادة معك دائماً أثناء القيادة، وعدم نسيانها في أي وقت. هذا سيساعدك على تجنب المخالفات المرورية والغرامات المالية.'}

In [ ]:
res3, docs3 = query_rag( 'ما هي غرامة التجمهر في موقع الحادث؟' )
res3

> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>التجمهر في موقع الحادث.</h1>
<p>الغرامة المالية 150 - 300 ريال</p>

<h1>إجراء سباق للمركبات على الطرق العامة، أو السير في مواكب دون الحصول على تصريح.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>التجمهر في مواقع التفحيط.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>الوقوف في أماكن وقوف ذوي الاحتياجات الخاصة من غير هذه الفئة المسموح لها.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>
السؤال: ما هي غرامة التجمهر في موقع الحادث؟
جوابك:


> Finished chain.

{'المخالفة': '<h1>التجمهر في موقع الحادث.</h1>\n<p>الغرامة المالية 150 - 300 ريال</p>\n\n<h1>إجراء سباق للمركبات على الطرق العامة، أو السير في مواكب دون الحصول على تصريح.</h1>\n<p>الغرامة المالية 3000 - 6000 ريال</p>\n\n<h1>التجمهر في مواقع التفحيط.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>الوقوف في أماكن وقوف ذوي الاحتياجات الخاصة من غير هذه الفئة المسموح لها.</h1>\n<p>الغرامة المالية 500 - 900 ريال</p>',
 'السؤال': 'ما هي غرامة التجمهر في موقع الحادث؟',
 'text': 'تتراوح غرامة التجمهر في موقع الحادث بين 150 و300 ريال سعودي. ننصحك بالابتعاد عن التجمهر في مواقع الحوادث لسلامتك وسلامة الآخرين، وعدم إعاقة حركة المرور.'}

In [ ]:
res3, docs3 = query_rag( 'ما هي غرامة عبور المشاة للطرق السريعة؟')
res3

> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>عبور المشاة للطرق السريعة.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>عبور المشاة للطرق من غير الأماكن المخصصة لهم.</h1>
<p>الغرامة المالية 100 - 150 ريال</p>

<h1>عدم إعطاء أفضلية المرور للمشاة أثناء عبورهم في المسارات المخصصة لهم.</h1>
<p>الغرامة المالية 100 - 150 ريال</p>

<h1>التجاوز في المناطق التي يمنع فيها التجاوز، مثل المنعطفات والمرتفعات.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>
السؤال: ما هي غرامة عبور المشاة للطرق السريعة؟
جوابك:


> Finished chain.

{'المخالفة': '<h1>عبور المشاة للطرق السريعة.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>عبور المشاة للطرق من غير الأماكن المخصصة لهم.</h1>\n<p>الغرامة المالية 100 - 150 ريال</p>\n\n<h1>عدم إعطاء أفضلية المرور للمشاة أثناء عبورهم في المسارات المخصصة لهم.</h1>\n<p>الغرامة المالية 100 - 150 ريال</p>\n\n<h1>التجاوز في المناطق التي يمنع فيها التجاوز، مثل المنعطفات والمرتفعات.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>',
 'السؤال': 'ما هي غرامة عبور المشاة للطرق السريعة؟',
 'text': 'تتراوح غرامة عبور المشاة للطرق السريعة بين 1000 و2000 ريال سعودي. ننصحك بالاحترام لتسليم الأماكن المخصصة للمشاة وعدم عبور الطرق السريعة في أي مكان سوى الأماكن المخصصة لهم، وذلك لحماية نفسك ونفس الآخرين.'}

In [ ]:
response, docs4 = query_rag("ماهي رؤية 2030؟")
response

> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>الرجوع إلى الخلف في الطريق العام لمسافة تزيد على عشرين متراً.</h1>
<p>الغرامة المالية 150 - 300 ريال</p>

<h1>عدم استخدام الأنوار اللازمة عند السير ليلاً أو في الأحوال الجوية التي تكون فيها الرؤية غير واضحة.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>زيادة أبعاد الحمولة المنقولة لمركبات النقل الثقيل على الحد المسموح به.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>
السؤال: ماهي رؤية 2030؟
جوابك:


> Finished chain.

{'المخالفة': '<h1>الرجوع إلى الخلف في الطريق العام لمسافة تزيد على عشرين متراً.</h1>\n<p>الغرامة المالية 150 - 300 ريال</p>\n\n<h1>عدم استخدام الأنوار اللازمة عند السير ليلاً أو في الأحوال الجوية التي تكون فيها الرؤية غير واضحة.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>\n\n<h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>\n<p>الغرامة المالية 3000 - 6000 ريال</p>\n\n<h1>زيادة أبعاد الحمولة المنقولة لمركبات النقل الثقيل على الحد المسموح به.</h1>\n<p>الغرامة المالية 1000 - 2000 ريال</p>',
 'السؤال': 'ماهي رؤية 2030؟',
 'text': 'أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. السؤال الذي طرحته لا يندرج تحت هذا السياق. إذا كان لديك سؤال عن مخالفة مرورية معينة، فسأكون سعيداً بمساعدتك.'}

In [ ]:
r = res.copy()

In [ ]:
print(f'المخالفات:\n{r["المخالفة"]}\n\nالسؤال:\n{r["السؤال"]}\n\n الاجابه:\n{r["text"]}')

المخالفات:
<h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع

<h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1>

جسم المركبة دون موافقة الجهات المختصة.</h1>

<h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح

السؤال:
ماهي الغرامة على القيادة بدون رخصة؟

 الاجابه:
قيمة الغرامة على القيادة بدون رخصة تتراوح بين 800 إلى 1,200 ريال سعودي. ننصحك بالحصول على رخصة قيادة سارية المفعول قبل قيادة أي مركبة، حيث أن القيادة بدون رخصة تهدد سلامتك وسلامة الآخرين، بالإضافة إلى مخالفة القوانين المرورية.

In [ ]:
for res, score in docs:
    print(f"* [SIM={score:3f}] {res.page_content} [{res.metadata}]")

* [SIM=297.101318] <h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع [{}]
* [SIM=311.606079] <h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1> [{}]
* [SIM=339.278137] جسم المركبة دون موافقة الجهات المختصة.</h1> [{}]
* [SIM=340.554108] <h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح [{}]

# Create a Chatbot with Gradio

In [ ]:
# Function to generate answer
def generate_answer(message, history):
    result = query_rag(message)
    return result[0]['text']

In [ ]:
answer_bot = gr.ChatInterface(
    generate_answer,
    chatbot=gr.Chatbot(height=400),
    textbox=gr.Textbox(placeholder="ادخل استفسارك هنا", container=False, scale=7),
    title="<div style='color: #57BE6A;'>اسألنــي</div>",
    description="<div style='text-align: center;'>نظام ذكي مصمم للاستعلام عن مخالفات المرور والغرامات في المملكة العربية السعودية بناءً على لائحة الجزاءات والمخالفات المرورية</div>",
    theme="JohnSmith9982/small_and_pretty",
    examples=["ما هي غرامة وقوف المركبة في أماكن غير مخصصة للوقوف؟", "ما هي غرامة عدم ربط حزام الأمان؟", "ما هي غرامة عدم الالتزام بحدود المسارات المحددة على الطريق؟"],
    cache_examples=False,
    submit_btn="إرسال",
    stop_btn="إيقاف",
)

if __name__ == "__main__":
    answer_bot.launch(debug=True)

/usr/local/lib/python3.10/dist-packages/gradio/components/chatbot.py:223: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  warnings.warn(

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://235c2d99ef22e4e762.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>عدم ربط حزام الأمان.</h1>
<p>الغرامة المالية 150 - 300 ريال</p>

<h1>عدم ارتداء الخوذة أثناء قيادة الدراجة الآلية.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>عدم الوقوف عند مراكز الضبط الأمني أو نقاط التفتيش أو عدم الوقوف للدورية الأمنية عند وجود توجيه أو علامة توجب الوقوف.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>عدم تغطية الحمولة المنقولة وتثبيتها.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>
السؤال: ما هي غرامة عدم ربط حزام الأمان؟
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>الوقوف في أماكن وقوف ذوي الاحتياجات الخاصة من غير هذه الفئة المسموح لها.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>

<h1>القيام بأعمال الطرق قبل التنسيق مع الإدارة المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>

<h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>سماح أصحاب الحيوانات بعبور حيواناتهم من غير الأماكن المخصصة لها، أو دون التنسيق مع الجهات المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>
السؤال: لدي استفسار اخر
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>الوقوف في أماكن وقوف ذوي الاحتياجات الخاصة من غير هذه الفئة المسموح لها.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>

<h1>القيام بأعمال الطرق قبل التنسيق مع الإدارة المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>

<h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>سماح أصحاب الحيوانات بعبور حيواناتهم من غير الأماكن المخصصة لها، أو دون التنسيق مع الجهات المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>
السؤال: لدي استفسار اخر
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>عدم حمل رخصة القيادة أو رخصة السير أثناء القيادة.</h1>
<p>الغرامة المالية 150 - 300 ريال</p>

<h1>قيادة المركبة برخصة قيادة لا تتناسب مع حجم المركبة ونوع استخدامها.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>قيادة مركبة دون توافر التجهيزات اللازمة، مثل المكابح والأنوار وما في حكمهما.</h1>
<p>الغرامة المالية 1000 - 2000 ريال</p>

<h1>عدم إعطاء أفضلية المرور في ملتقيات الطرق أو تقاطعاتها لسائق المركبة المتقدم على غيره في حال عدم وجود لوحات تنظم ذلك.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>
السؤال: ما هي غرامة عدم حمل رخصة القيادة اثناء القياده؟
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>تجاوز إشارة المرور الضوئية أثناء الضوء الأحمر.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>عدم الوقوف وقوفاً تاماً عند إشارة (أمامك أفضلية) في حالة مرور مركبات على الطريق المعطاة له الأفضلية.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>

<h1>عدم إعطاء الأفضلية للمركبات التي بداخل الدوار من قبل المركبات التي خارجه في حالة عدم وجود إشارات ضوئية أو رجل أمن يوجه السير.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>

<h1>عدم إعطاء الأفضلية للمركبة القادمة من اليمين عند الوصول إلى تقاطع متساوي الأفضلية في آن واحد وعندما لا يكون هناك إشارات أولوية.</h1>
<p>الغرامة المالية 500 - 900 ريال</p>
السؤال: ما هي غرامة تجاوز اشارة المرور اثناء الضوء الاحمر؟
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>القيام بأعمال الطرق قبل التنسيق مع الإدارة المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>

<h1>استخدام أجهزة غير مصرح بها في المركبة أو وضع شعارات أو ملصقات تتنافى مع الآداب العامة.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>تسيير مركبات الأشغال العامة على الطرق قبل اتخاذ الإجراءات اللازمة لتلافي أضرارها، بما في ذلك عدم وضع الشرائح العاكسة على جانبي مؤخرة المركبة.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>
السؤال: ما هو نظام ابشر؟
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>القيام بأعمال الطرق قبل التنسيق مع الإدارة المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>

<h1>استخدام أجهزة غير مصرح بها في المركبة أو وضع شعارات أو ملصقات تتنافى مع الآداب العامة.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>تسيير مركبات الأشغال العامة على الطرق قبل اتخاذ الإجراءات اللازمة لتلافي أضرارها، بما في ذلك عدم وضع الشرائح العاكسة على جانبي مؤخرة المركبة.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>
السؤال: ما هو نظام ابشر؟
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.



**ملاحظات هامة:**

* **الخصوصية:** يرجى العلم أن جميع المعلومات المقدمة ستعامل بسرية تامة.

* **الدقة:** تأكد من صحة المعلومات التي تقدمها للحصول على نتائج دقيقة.

قد يسأل المستخدم عن سؤال خارج نظام المرور، لذلك يمكنك الامتناع عن الاجابة (مثال: أعتذر، ولكن النظام مصمم للإجابة عن استفسارات تتعلق بالمخالفات المرورية والغرامات. )

**مثال على الحوار:**



**المستخدم:** ما هي قيمة غرامة عدم ارتداء حزام الأمان؟

**النظام:** تتراوح غرامة عدم ارتداء حزام الأمان بين 150 و300 ريال سعودي. احرص على ارتدائه دائماً. ننصحك بارتداء حزام الأمان في كل الأوقات لسلامتك وسلامة الآخرين.

المخالفة: <h1>تركيب تجهيزات في المركبة كتلك الخاصة بالمركبات الرسمية ومركبات الطوارئ.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>القيام بأعمال الطرق قبل التنسيق مع الإدارة المختصة.</h1>
<p>الغرامة المالية 5000 - 10000 ريال</p>

<h1>استخدام أجهزة غير مصرح بها في المركبة أو وضع شعارات أو ملصقات تتنافى مع الآداب العامة.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>

<h1>تسيير مركبات الأشغال العامة على الطرق قبل اتخاذ الإجراءات اللازمة لتلافي أضرارها، بما في ذلك عدم وضع الشرائح العاكسة على جانبي مؤخرة المركبة.</h1>
<p>الغرامة المالية 3000 - 6000 ريال</p>
السؤال: ما هو نظام ابشر؟
جوابك:


> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:

## التعليمات:



**المهمة:**

* أنت نظام ذكي متخصص في الاستعلام عن المخالفات المرورية في المملكة العربية السعودية.

* ستُزود بمعلومات عن المخالفة المرورية التي يرغب المستخدم في الاستعلام عنها.

* يجب عليك توفير إجابات مفصلة وشاملة بناءً على المعلومات المتاحة.

* تأكد من تقديم نصائح مفيدة باللغة العربية تتناسب مع سياق المخالفة.

* احرص على الالتزام بالمعلومات المقدمة وعدم الخروج عن سياق المخالفة.

* يجب عليك عدم الخروج عن المعلومات المسجلة في النظام.

* اذا كانت المخالفة المزوده لك ليست ذات صلة، يمكنك اخبار المستخدم بإنك لا تعرف الاجابة.

* يجب عليك ارجاع الغرامة بشكل صحيح حسب نظام المرور وحسب سؤال المستخدم.



**أسئلة الاستعلام:**

* **قيمة الغرامة:** استفسار عن قيمة الغرامة المالية المترتبة على المخالفة.



**أمثلة على صياغة الأسئلة:**

* "ما هي قيمة غرامة تجاوز السرعة بـ 30 كم/ساعة؟"



**الردود المتوقعة:**

* **معلومات دقيقة:** سيتم تقديم معلومات دقيقة عن الغرامة بناءً على قاعدة البيانات المتاحة.

* **نصائح مفيدة:** سيتم تقديم نصائح باللغة العربية حول كيفية تجنب تكرار المخالفة.

* **إجابات مفتوحة:** في حالة عدم توفر معلومات كافية، سيتم توجيه المستخدم إلى الاتصال بمركز خدمات المرور للحصول على المساعدة.


